added formatting features to live and pre-recorded transcriptions
deepgram/deepgram-node-sdk pull request #85
Opened 2022-10-31 20:43 UTC by briancbarrow

2022-10-31 21:13 UTC, shirgoldbird requested changes
Thank you so much! Requested a few changes

2022-10-31 21:13 UTC, shirgoldbird commented on src/types/liveTranscriptionOptions.ts
> +  numbers_space?: boolean;
Should be plural: `numbers_spaces`

2022-10-31 21:13 UTC, shirgoldbird commented on src/types/prerecordedTranscriptionOptions.ts
> +  numbers?: boolean;
Same comment here, we should keep `numerals` around for now

2022-10-31 21:13 UTC, shirgoldbird commented on src/types/prerecordedTranscriptionOptions.ts
> +  numbers_space?: boolean;
Plural: `numbers_spaces`

2022-10-31 21:13 UTC, shirgoldbird commented on src/types/prerecordedTranscriptionOptions.ts
> +  numbers?: boolean;
Same comment here, we should keep `numerals` around for now

2022-10-31 21:13 UTC, shirgoldbird commented on src/types/usageOptions.ts
> -  numerals?: boolean;
Keep numerals

2022-10-31 21:13 UTC, shirgoldbird commented on src/types/usageRequestDetail.ts
> -      numerals?: boolean;
Keep numerals

2022-10-31 22:05 UTC, shirgoldbird commented on src/types/liveTranscriptionOptions.ts
> +  datetime?: boolean;
Can you remove all the `datetime` and `datetime_format` options? I realized this feature doesn't exist yet... 😅

2022-11-01 16:26 UTC, briancbarrow commented on src/types/liveTranscriptionOptions.ts
> -  numerals?: boolean;
So do we want to have both `numbers` and `numerals`?

2022-11-01 20:10 UTC, shirgoldbird approved these changes
LGTM! Thank you 🙏🏻

2022-11-15 19:35 UTC, merged